apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-java-app-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: pvc-ddaf598f-6665-421f-bd86-c51e5d6e12bc
    fsType: ext4 # or your preferred file system

